<?php

class SearchUrl{
    public $url;
    public $displayUrl;
    public $title;
    public $description;

    public function define($aurl, $adisplayUrl, $atitle, $adescription) {
        $this->url = $aurl;
        $this->displayUrl = $adisplayUrl;
        $this->title = $atitle;
        $this->description = $adescription;
    }
}

class SearchUrls{

    public $urls = array();

    function get() {
        return $this->urls;
    }

    function getUrl($urlkey) {
        return $this->urls[$urlkey];
    }

    function create(){

        // naively copy and pasted from Java then find and and replace to create PHP code
        // A bunch of urls scraped from searches - webdriver, java enums, java for testers, eviltester, stafford beer - to simulate a search engine
        $aUrl = new SearchUrl(); $aUrl->define("http://docs.seleniumhq.org/projects/webdriver/", "docs.seleniumhq.org/projects/webdriver", "Selenium WebDriver", "Selenium WebDriver. The biggest change in Selenium recently has been the inclusion of the WebDriver API. Driving a browser natively as a user would either locally or ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://docs.seleniumhq.org/docs/03_webdriver.jsp", "docs.seleniumhq.org/docs/03_webdriver.jsp", "Selenium WebDriver Selenium Documentation", "Introducing WebDriverÂ¶ The primary new feature in Selenium 2.0 is the integration of the WebDriver API. WebDriver is designed to provide a simpler, more concise ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://seleniumhq.github.io/docs/", "https://seleniumhq.github.io/docs", "Selenium Documentation", "The Selenium Browser Automation Project. Selenium is an umbrella project for a range of tools and libraries that enable and support the automation of web browsers.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikipedia.org/wiki/WebDriver", "https://en.wikipedia.org/wiki/WebDriver", "Selenium (software) - Wikipedia, the free encyclopedia", "Selenium is a portable software testing framework for web applications. Selenium provides a record/playback tool for authoring tests without learning a test scripting ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.aosabook.org/en/selenium.html", "www.aosabook.org/en/selenium.html", "Selenium WebDriver - aosabook.org", "Selenium is a browser automation tool, commonly used for writing end-to-end tests of web applications. A browser automation tool does exactly what you would expect ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://seleniumjava.com/", "https://seleniumjava.com", "Selenium WebDriver Test Automation For Manual Testers", "While developing the Selenium WebDriver test automation scripts, the scripts are executed within Eclipse. But as soon as the scripts work as expected, you may want to ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://github.com/seleniumhq/selenium-google-code-issue-archive", "https://github.com/seleniumhq/selenium-google-code-issue-archive", "GitHub - SeleniumHQ/selenium-google-code-issue-archive ...", "selenium-google-code-issue-archive - Archive, please see main selenium repo. Skip to content. Personal Open source Business Explore Sign up Sign in.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://github.com/SeleniumHQ/selenium", "https://github.com/SeleniumHQ/selenium", "GitHub - SeleniumHQ/selenium: A browser automation ...", "selenium - A browser automation ... Selenium specifically provides infrastructure for the W3C WebDriver specification â€” a platform and language-neutral coding ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www.seleniumhq.org/", "https://www.seleniumhq.org", "Selenium IDE Addons", "'Real' content to be added later, but this is prettier than the default static page.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://stackoverflow.com/questions/tagged/selenium-webdriver", "stackoverflow.com/questions/tagged/selenium-webdriver", "Newest 'selenium-webdriver' Questions - Stack Overflow", "Selenium-WebDriver provides the WebDriver API for controlling browsers in different programming languages ('language bindings'). When using this tag, also add a tag ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www.npmjs.com/package/selenium-webdriver", "https://www.npmjs.com/package/selenium-webdriver", "Selenium WebDriver JS - npm", "selenium-webdriver. Selenium is a browser automation library. Most often used for testing web-applications, Selenium may be used for any task that requires automating ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.nuget.org/packages/Selenium.WebDriver", "www.nuget.org/packages/Selenium.WebDriver", "NuGet Gallery | Selenium WebDriver 2.53.0", "Contact Us. Got questions about NuGet or the NuGet Gallery? Overview. NuGet is a Visual Studio extension that makes it easy to add, remove, and update libraries and...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://webdriver.io/", "webdriver.io", "WebdriverIO - Selenium 2.0 javascript bindings for nodejs", "Feature-Rich. Most of the Selenium WebDriver Wire Protocol is already implemented and wrapped in useful commands");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://rubygems.org/gems/selenium-webdriver/versions/2.53.0", "https://rubygems.org/gems/selenium-webdriver/versions/2.53.0", "selenium-webdriver | RubyGems.org | your community gem host", "WebDriver is a tool for writing automated tests of websites. It aims to mimic the behaviour of a real user, and as such interacts with the HTML of the application.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://docs.seleniumhq.org/projects/remote-control/", "docs.seleniumhq.org/projects/remote-control", "Selenium Remote-Control", "Selenium RC comes in two parts. ... Selenium Remote Control is great for testing complex AJAX-based web user interfaces under a Continuous Integration system.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://docs.seleniumhq.org/docs/05_selenium_rc.jsp", "docs.seleniumhq.org/docs/05_selenium_rc.jsp", "Selenium 1 (Selenium RC) â€” Selenium Documentation", "How Selenium RC WorksÂ¶ First, we will describe how the components of Selenium RC operate and the role each plays in running your test scripts.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://compendiumdev.co.uk/selenium/mindmap/Selenium-RC_Commands.html", "compendiumdev.co.uk/selenium/mindmap/Selenium-RC_Commands.html", "Selenium-RC Commands - Compendium Dev", "Selenium-RC Commands Selenium-RC Commands ... http://clearspace.openqa.org/community/selenium/blog/2009/01/13/selenium-rc-beta-2-goodies-and-gotchas");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikipedia.org/wiki/Selenium_RC", "https://en.wikipedia.org/wiki/Selenium_RC", "Selenium (software) - Wikipedia, the free encyclopedia", "Selenium is a portable software testing framework for web applications. Selenium provides a record/playback tool for authoring tests without learning a test scripting ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www.scribd.com/doc/315320389/Selenium-RC", "https://www.scribd.com/doc/315320389/Selenium-RC", "Selenium RC - scribd.com", "Test Automation Using. Selenium 1 Selenium RC A solution to cross browser testing. A server, written in Java and so available on all the platforms.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://stackoverflow.com/questions/tagged/selenium-rc", "stackoverflow.com/questions/tagged/selenium-rc", "Newest 'selenium-rc' Questions - Stack Overflow", "I have a requirement where i have to pass the values for a bootstrap drop down menu using selenium instead of selecting. How can i achieve this?");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.nuget.org/packages/Selenium.RC", "www.nuget.org/packages/Selenium.RC", "NuGet Gallery | Selenium Remote Control (RC) 2.53.0", "Contact Us. Got questions about NuGet or the NuGet Gallery? Overview. NuGet is a Visual Studio extension that makes it easy to add, remove, and update libraries and...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.tutorialspoint.com/selenium/selenium_rc.htm", "www.tutorialspoint.com/selenium/selenium_rc.htm", "Selenium - Remote Control - Tutorialspoint", "Selenium Remote Control (RC) was the main Selenium project that sustained for a long time before Selenium WebDriver(Selenium 2.0) came into existence.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.hasanaziz.co.uk/tag/seleniumrc/", "www.hasanaziz.co.uk/tag/seleniumrc", "Selenium RC | Hasan's Agile Testing Blog", "Two years ago, while working at the The Trainilne, I was part of the Automated Refunds project and the main QA/Developer for its automated test framework.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://saucelabs.com/selenium/selenium-rc", "https://saucelabs.com/selenium/selenium-rc", "Upgrading from Selenium RC to WebDriver - Sauce Labs", "Upgrading from Selenium RC to WebDriver As the Selenium project continues to evolve, Selenium RC is moving closer to end-of-life. This is especially true with the ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.methodsandtools.com/tools/tools.php?selenium", "www.methodsandtools.com/tools/tools.php?selenium", "Automated WebTesting with Selenium RC - Methods & Tools", "Automated WebTesting with Selenium RC. ... Selenium RC is a client/server based application that allows you to control web browsers using the following components.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://release.seleniumhq.org/selenium-remote-control/0.9.2/doc/java/com/thoughtworks/selenium/Selenium.html", "release.seleniumhq.org/selenium-remote-control/0.9.2/doc/java/com/...", "Selenium (Selenium RC Java Client Driver 0.9.2 API)", "public interface Selenium. Defines an object that runs Selenium commands. Element Locators. Element Locators tell Selenium which HTML element a command refers to.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikipedia.org/wiki/Abstraction_layer", "https://en.wikipedia.org/wiki/Abstraction_layer", "Abstraction layer - Wikipedia, the free encyclopedia", "In computing, an abstraction layer or abstraction level is a way of hiding the implementation details of a particular set of functionality, allowing the separation of ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikipedia.org/wiki/Database_abstraction_layer", "https://en.wikipedia.org/wiki/Database_abstraction_layer", "Database abstraction layer - Wikipedia, the free encyclopedia", "A database abstraction layer is an application programming interface which unifies the communication between a computer application and databases such as SQL Server ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://whatis.techtarget.com/definition/hardware-abstraction-layer-HAL", "whatis.techtarget.com/definition/hardware-abstraction-layer-HAL", "What is hardware abstraction layer (HAL)? - Definition ...", "1) In computers, a hardware abstraction layer (HAL) is a layer of programming that allows a computer operating system to interact with a hardware device at a general ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://encyclopedia2.thefreedictionary.com/Abstraction+layer", "encyclopedia2.thefreedictionary.com/Abstraction+layer", "Abstraction layer | Article about abstraction layer by The ...", "abstraction layer Software that translates a high-level request into the low-level commands required to perform the operation. The most common abstraction layer is ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.pcmag.com/encyclopedia/term/37353/abstraction-layer", "www.pcmag.com/encyclopedia/term/37353", "abstraction layer Definition from PC Magazine Encyclopedia", "Software that translates a high-level request into the low-level commands required to perform the operation. The most common abstraction layer is the programming ...");

        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.eviltester.com/", "www.eviltester.com", "Home | EvilTester.com", "Recent posts on EvilTester.com. Subscribe to our Newsletter. We periodically send out a newsletter of information we hope will interest and benefit you.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://blog.eviltester.com/", "blog.eviltester.com", "Evil Tester", "After publishing â€œDear Evil Testerâ€ I forgot to setup a Google Alert, but I set one up a few days ago and this morning it picked up a book review.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.youtube.com/user/EviltesterVideos", "www.youtube.com/user/EviltesterVideos", "Evil Tester - YouTube", "Evil Tester : http://eviltester.com Selenium Simplified: ... The Evil Tester's Guide to Technical Testing - EuroSTAR - Alan Richardson - Duration: 54 minutes.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://github.com/eviltester", "https://github.com/eviltester", "eviltester Â· GitHub", "eviltester has 40 repositories written in Shell, JavaScript, and C++. Follow their code on GitHub.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://blog.eviltester.com/2015/01/some-api-testing-basic-introductory.html", "blog.eviltester.com/2015/01/some-api-testing-basic-introductory.html", "Evil Tester: Some API Testing Basic Introductory Notes and ...", "Some applications provide an API. Some websites provide an API. This post provides some information on API testing, since that appears to have consume a lot of my ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://github.com/eviltester/javaForTestersCode", "https://github.com/eviltester/javaForTestersCode", "GitHub - eviltester/javaForTestersCode: Java source code ...", "javaForTestersCode - Java source code to support the book 'Java For Testers'");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://eviltester.com/page/contact/", "eviltester.com/page/contact", "Home | EvilTester.com", "Toggle navigation EvilTester.com. About The Book; Read The Blog; Contact; EvilTester.com Contact Form. Your Email: Your Name: Message:");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://thesocialtester.co.uk/", "thesocialtester.co.uk", "START - The Social Tester", "Hello and welcome to The Social Tester blog by Rob Lambert. Announcement - a new book with my best articles from this blog and some previously unpublished material ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://javafortesters.com/", "javafortesters.com", "Java For Testers - Learn to Code Java With Tests", "Book Java For Testers - Learn to Code Java With Tests");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://uk.linkedin.com/in/eviltester", "https://uk.linkedin.com/in/eviltester", "Alan Richardson | LinkedIn", "View Alan Richardson's professional profile on LinkedIn. LinkedIn is the world's largest business network, helping professionals like Alan Richardson discover ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www.testnet.org/testnet/download/evenement-voorjaar-2013/alan_richardson_testerguidetohttpproxies.pdf", "https://www.testnet.org/testnet/download/evenement-voorjaar-2013/...", "www.eviltester.com @eviltester www.compendiumdev.co.uk ...", "The Evil Tester's Guide to HTTP Proxies A Tutorial for TestNet May 2013 Alan Richardson @eviltester www.eviltester.com www.compendiumdev.co.uk www.seleniumsimplified.com");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://javafortesters.com/page/buy/", "javafortesters.com/page/buy", "Java For Testers - Learn to Code Java With Tests", "How to Buy Java For Testers book and eBook. ... @eviltester Thank you for writing #JavaForTesters Great Help! Vineet Kumar (@binnythetester) May 4, 2015");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://lets-test.com/wp-content/uploads/2013/06/The-Evil-Testers-Guide-to-Web-Testing.pdf", "lets-test.com/wp-content/.../The-Evil-Testers-Guide-to-Web-Testing.pdf", "www.eviltester.com The Evil Tester's Guide to www ...", "The Evil Tester's Guide to Technical Web Testing Let's Test 2013 Alan Richardson @eviltester www.eviltester.com www.compendiumdev.co.uk www.seleniumsimplified.com");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.bcs.org/content/ConMediaFile/27031", "www.bcs.org/content/ConMediaFile/27031", "Push Your Functional Testing Further - bcs.org", "Push Your Functional Testing Further Alan Richardson EvilTester.com @EvilTester Technology and Security into");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.slideshare.net/eviltester", "www.slideshare.net/eviltester", "Alan Richardson presentations | SlideShare", "Alan Richardson Following Follow 39 SlideShares; ... Website http://www.eviltester.com; About I work as an independent test consultant, trainer, author and contractor.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www.testingcircus.com/an-interview-with-alan-richardson/", "https://www.testingcircus.com/an-interview-with-alan-richardson", "An Interview with Alan Richardson @EvilTester - Testing Circus", "An Interview with Alan Richardson @EvilTester. Author of the books Selenium Simplified and Java For Testers, Alan also has created online training courses to help ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://eviltester.wordpress.com/", "https://eviltester.wordpress.com", "Evil Tester â€“ Software QA Testing", "Almost certain that the risk will not happen. Low potential. Can happen in very specific circumstances");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.compendiumdev.co.uk/page.php?title=blogs", "www.compendiumdev.co.uk/page.php?title=blogs", "Blogs - Compendium Dev", "Blogs and News. Compendium ... EvilTester Blog . National Software Testing Conference 2016; How to Watch Repositories on Github via a NewsFeed; Behind the Scenes: ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.compendiumdev.co.uk/", "www.compendiumdev.co.uk", "Software Testing Essays, Book Reviews and Information", "Software testing and software quality essays, book reviews, and tools. Authors of Compendium-TA, a commercial modeling tool.");

        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html", "https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html", "Enum Types (The Javaâ„¢ Tutorials > Learning the Java ...", "Java programming language enum types are much more powerful than their counterparts in other languages. The enum declaration defines a class (called an enum type).");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html", "https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html", "Enum (Java Platform SE 7 ) - Oracle Help Center", "This is the common base class of all Java language enumeration types. More information about enums, including descriptions of the implicitly declared methods ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://tutorials.jenkov.com/java/enums.html", "tutorials.jenkov.com/java/enums.html", "Java Enums - Jenkov.com", "A Java Enum is a special Java type used to define collections of constants. More precisely, a Java enum type is a special kind of Java class.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://crunchify.com/why-and-for-what-should-i-use-enum-java-enum-examples/", "crunchify.com/why-and-for-what-should-i-use-enum-java-enum-examples", "Beginner's Guide to Java eNum - Why and for What should I ...", "Beginnerâ€™s Guide to Java eNum â€“ Why and for What should I use Enum? Java Enum Examples. Short link: Last Updated on June 6th, 2016 by Crunchify 16 Comments");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://javarevisited.blogspot.com/2011/08/enum-in-java-example-tutorial.html", "javarevisited.blogspot.com/2011/08/enum-in-java-example-tutorial.html", "Java Enum Tutorial: 10 Examples of Enum in Java", "What is Enum in Java Enum in Java is a keyword, a feature which is used to represent fixed number of well-known values in Java, For example, Number of days in Week ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://javahowto.blogspot.com/2008/04/java-enum-examples.html", "javahowto.blogspot.com/2008/04/java-enum-examples.html", "Java How To ...: Java enum examples", "Simple enum. The ; after the last element is optional, when this is the end of enum definition. public enum Color { WHITE, BLACK, RED, YELLOW, BLUE; //; is ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.mkyong.com/java/java-enum-example/", "www.mkyong.com/java/java-enum-example", "Java enum example - Mkyong", "Some of the Java enum examples, and how to use it, nothing special, just for self-reference.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://stackoverflow.com/questions/4709175/what-are-enums-and-why-are-they-useful", "stackoverflow.com/questions/4709175/what-are-enums-and-why-are...", "java - What are enums and why are they useful? - Stack ...", "Today I was browsing through some questions on this site and I found a mention of an enum being used in singleton pattern about purported thread safety benefits to ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://howtoprogramwithjava.com/enums/", "https://howtoprogramwithjava.com/enums", "Enums â€“ How to Program with Java â€“ Java Tutorial", "Enums is a neat topic that applies to most programming languages (not just Java)! What is an Enum? Itâ€™s short for Enumerated Type, which just means that Ja");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://developer.android.com/reference/java/lang/Enum.html", "https://developer.android.com/reference/java/lang/Enum.html", "Enum | Android Developers", "Parameters; name: String: the enum constant's declared name. ordinal: int: the enum constant's ordinal, which corresponds to its position in the ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www-users.cs.york.ac.uk/~pcairns/papers/Enums.pdf", "https://www-users.cs.york.ac.uk/~pcairns/papers/Enums.pdf", "Enumerated Types in Java", "2 SUMMARY Java does not contain enumerated types. This paper demonstrates how to produce classes that behave like enumerated types with secure,");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikipedia.org/wiki/Enumerated_type", "https://en.wikipedia.org/wiki/Enumerated_type", "Enumerated type - Wikipedia, the free encyclopedia", "In computer programming, an enumerated type (also called enumeration or enum, or factor in the R programming language, and a categorical variable in statistics) is a ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.javatpoint.com/enum-in-java", "www.javatpoint.com/enum-in-java", "Java Enum - javatpoint", "Defining Java enum. The enum can be defined within or outside the class because it is similar to a class. Java enum example: defined outside class");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://alvinalexander.com/java/using-java-enum-examples-tutorial", "alvinalexander.com/java/using-java-enum-examples-tutorial", "Java enum examples/tutorial | Java enum constant, for loop ...", "Examples of the Java enum, including how to declare a Java enum, and how to use a Java enum in a for loop, switch statement, and if/else statement.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www.ntu.edu.sg/home/ehchua/programming/java/JavaEnum.html", "https://www.ntu.edu.sg/home/ehchua/programming/java/JavaEnum.html", "Enum - Java Programming Tutorial", "For each enum, the Java compiler automatically generates a static method called values() that returns an array of all the enum constants, in the order they were defined.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://developer.android.com/reference/java/lang/Enum.html", "developer.android.com/reference/java/lang/Enum.html", "Enum | Android Developers", "Compares this object to the specified enum object to determine their relative order.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/lang/Enum.java", "grepcode.com/.../java/root/jdk/openjdk/6-b14/java/lang/Enum.java", "GC: Enum - java.lang.Enum (.java) - GrepCode Class Source", "java.lang.Enum - This is the common base class of all Java language enumeration types");

        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikipedia.org/wiki/Edsger_W._Dijkstra", "https://en.wikipedia.org/wiki/Edsger_W._Dijkstra", "Edsger W. Dijkstra - Wikipedia, the free encyclopedia", "Biography Early years. Edsger W. Dijkstra was born in Rotterdam. His father was a chemist who was president of the Dutch Chemical Society; he taught chemistry at a ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.cs.utexas.edu/users/EWD/", "www.cs.utexas.edu/users/EWD", "E.W.Dijkstra Archive: Home page", "Manuscripts of Edsger W. Dijkstra, a collection of over 1,300 written works, famously known as EWDs. Also, In Pursuit of Simplicity symposium. Format: PDF.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikiquote.org/wiki/Edsger_W._Dijkstra", "https://en.wikiquote.org/wiki/Edsger_W._Dijkstra", "Edsger W. Dijkstra - Wikiquote", "Misattributed . Go To statement considered harmful Dijkstra sent a paper to Communications of the ACM under the title of 'A Case against the GO TO Statement' (EWD215 ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm", "https://en.wikipedia.org/wiki/Dijkstra's_algorithm", "Dijkstra's algorithm - Wikipedia, the free encyclopedia", "Dijkstra's algorithm to find the shortest path between a and b. It picks the unvisited vertex with the lowest distance, calculates the distance through it ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://amturing.acm.org/award_winners/dijkstra_1053701.cfm", "amturing.acm.org/award_winners/dijkstra_1053701.cfm", "Edsger W. Dijkstra - A.M. Turing Award Winner", "Edsger W. Dijkstra was born in 1930 in Rotterdam, The Netherlands. His father, a high-school chemistry teacher, served as president of the Dutch Chemical Society.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.braindash.com/quotes/e_w_dijkstra/the_question_of_whether_a_computer_can_think_is_no_more_interesting_than_the_question_of_whether_a_s/", "www.braindash.com/quotes/e_w_dijkstra/the_question_of_whether_a...", "E. W. Dijkstra: The question of whether a computer can ...", "E. W. Dijkstra - Famous quotes including 'The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.'");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.thocp.net/biographies/dijkstra_edsger.htm", "www.thocp.net/biographies/dijkstra_edsger.htm", "Edsger Wybe Dijkstra - History of computing", "Edsger Wybe Dijkstra 11 May 1930, Rotterdam, Netherlands 6 August 2002, Nuenen, Netherlands. the core of this page is based on Mike Nussdorfer's page");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.cs.utexas.edu/users/EWD/index08xx.html", "www.cs.utexas.edu/users/EWD/index08xx.html", "E.W.Dijkstra Archive: Index EWD 800-899", "821: 40: From predicate transformers to predicates (Dedicated by the Tuesday Afternoon Club to C.A.R. Hoare at the occasion of his being elected Fellow of the Royal ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.quotationspage.com/quotes/E._W._Dijkstra", "www.quotationspage.com/quotes/E._W._Dijkstra", "E. W. Dijkstra Quotes - The Quotations Page", "E. W. Dijkstra The fathers of the field had been pretty confusing: John von Neumann speculated about computers and the human brain in analogies sufficiently wild to ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://hocc.swansea.ac.uk/node/45", "hocc.swansea.ac.uk/node/45", "E W Dijkstra | History of Computing Collection", "The Collection. Special Collections; Computers and Software; Education and Research; People and Reminiscences. Biographies. E W Dijkstra; Hartill, Rob; de Roever ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://math.mit.edu/~rothvoss/18.304.3PM/Presentations/1-Melissa.pdf", "math.mit.edu/~rothvoss/18.304.3PM/Presentations/1-Melissa.pdf", "DIJKSTRAâ€™S ALGORITHM - MIT Mathematics", "Dijkstraâ€™s Algorithm ! Solution to the single-source shortest path problem in graph theory ! Both directed and undirected graphs ! All edges must have ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html", "www.u.arizona.edu/.../Go_To_Considered_Harmful.html", "Go To Statement Considered Harmful - University of Arizona", "Go To Statement Considered Harmful Edsger W. Dijkstra. Reprinted from Communications of the ACM, Vol. 11, ... (i.e. everything except, perhaps, plain machine code).");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.zoominfo.com/p/E.-Dijkstra/780990190", "www.zoominfo.com/p/E.-Dijkstra/780990190", "E. Dijkstra | ZoomInfo.com", "View E. Dijkstra's business profile and see work history, affiliations and more.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.zoominfo.com/p/E.-Dijkstra/244660545", "www.zoominfo.com/p/E.-Dijkstra/244660545", "E. Dijkstra | University of Texas at Austin | ZoomInfo.com", "View E. Dijkstra's business profile as Chairman Emeritus Department of Computer Science at University of Texas at Austin and see work history, affiliations and more.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://wikipedia.or.ke/index.php/Edsger_W._Dijkstra", "wikipedia.or.ke/index.php/Edsger_W._Dijkstra", "Edsger W. Dijkstra - Wikipedia", "Template:Infobox scientist Edsger Wybe Dijkstra (Template:IPA-nl; May 11, 1930 â€“ August 6, 2002) was a Dutch computer scientist. He received the 1972 Turing Award ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.inf.ed.ac.uk/teaching/courses/dmmr/slides/13-14/lec-shortest-coloring.pdf", "www.inf.ed.ac.uk/teaching/courses/dmmr/slides/13-14/lec-shortest...", "Shortest Paths, and Dijkstra's Algorithm: Overview - Ed", "Dijkstra's single-source shortest-path algorithm Input: Edge-weighted graph, G = ( V ; E ; w ), with ( extended ) weight function w : V V ! N , and a source vertex s ...");

        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://javafortesters.com/", "javafortesters.com", "Java For Testers - Learn to Code Java With Tests", "Book Java For Testers - Learn to Code Java With Tests");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://leanpub.com/javaForTesters", "https://leanpub.com/javaForTesters", "Java For Testers by Alan Richardson [Leanpub PDF/iPad/Kindle]", "Java For Testers: a book designed to teach the fundamentals of Java by writing JUnit @Test methods");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.compendiumdev.co.uk/page.php?title=javafortestersbook", "www.compendiumdev.co.uk/page.php?title=javafortestersbook", "Java For Testers - Compendium Dev", "Java For Testers. People ask me what books I recommend to learn Java. And I have a few books that I thoroughly recommend, but they are not aimed at beginners.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://javafortesters.com/page/install/", "javafortesters.com/page/install", "Java For Testers - Learn to Code Java With Tests", "Install Software for Java For Testers. This page is a summary of the resources to help with installation of the Software required to work with the Java For Testers book.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://leanpub.com/javaForTesters/read", "https://leanpub.com/javaForTesters/read", "Read Java For Testers | Leanpub", "Welcome to this Sample. Hi, Welcome to this sample of â€œJava For Testersâ€ by Alan Richardson. This sample is free, and contains the early chapters of the full book ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://blog.javafortesters.com/", "blog.javafortesters.com", "Java For Testers", "I previously mentioned that â€œJava For Testersâ€ teaches Java without writing main methods, and in fact uses @Test annotated methods for all of its code.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.amazon.com/Java-Testers-Learn-fundamentals-fast/dp/0956733255", "www.amazon.com/Java-Testers-Learn-fundamentals-fast/dp/0956733255", "Java For Testers: Learn Java fundamentals fast: Mr Alan J ...", "Java For Testers: Learn Java fundamentals fast [Mr Alan J Richardson] on Amazon.com. *FREE* shipping on qualifying offers. This book is for people who want to learn Java.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www.amazon.com/Java-Testers-Learn-fundamentals-fast-ebook/dp/B00U618KNC", "https://www.amazon.com/Java-Testers-Learn-fundamentals-fast-ebook/...", "Java For Testers: Learn Java fundamentals fast 1, Alan ...", "Java For Testers: Learn Java fundamentals fast - Kindle edition by Alan Richardson. Download it once and read it on your Kindle device, PC, phones or tablets. Use ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://seleniumsimplified.com/2013/06/new-book-java-for-testers/", "seleniumsimplified.com/2013/06/new-book-java-for-testers", "New Book â€œJava For Testersâ€ Â» Selenium Simplified", "Most of the Selenium WebDriver work I do uses Java. When I wrote the Selenium Simplified book, I was trying to teach Java, at the same time as Selenium-RC.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://blog.javafortesters.com/p/about-book.html", "blog.javafortesters.com/p/about-book.html", "Java For Testers: About the Book", "And since the book is mainly aimed at testers, and working towards testers creating abstraction layers for test automation:");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.allitebooks.com/java-for-testers/", "www.allitebooks.com/java-for-testers", "Java For Testers - pdf - Free IT eBooks Download", "This book is for people who want to learn Java. Particularly people on a team that want to learn Java, but who aren't going to be coding the main Java appl");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://github.com/eviltester/javaForTestersCode", "https://github.com/eviltester/javaForTestersCode", "java For Testers Source Code - GitHub", "javaForTestersCode - Java source code to support the book 'Java For Testers'");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://stackoverflow.com/questions/1555816/java-interview-questions-for-software-tester", "stackoverflow.com/questions/1555816", "testing - Java: Interview questions for software tester ...", "These days I have an interview for the position: Software Testing Engineer. Any ideas what questions might pop to the interview? Any tips?");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.joecolantonio.com/2013/10/24/book-review-java-for-testers-learn-java-fundamentals-fast/", "www.joecolantonio.com/...java-for-testers-learn-java-fundamentals-fast", "Book Review: Java For Testers Learn Java Fundamentals Fast!", "Book Review: Java For Testers. Java For Testers: Learn Java Fundamentals Fast by Alan Richardson Leanpub $4.99 â€“ $24.99. I am repeatedly asked the following ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.oracle.com/technetwork/articles/java/unittesting-455385.html", "www.oracle.com/technetwork/articles/java/unittesting-455385.html", "Unit Testing for Java EE - Oracle", "Unit Testing for Java EE. By Adam Bien. Think testing Java EE applications is difficult, inconvenient, or too complex? Learn why this isn't the case and how do unit ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.youtube.com/playlist?list=PLrM2ELpRbbu6QVVh74SjN9nLSOutUBbLb", "www.youtube.com/playlist?list=PLrM2ELpRbbu6QVVh74SjN9nLSOutUBbLb", "Java For Testers - YouTube", "Evil Tester; Videos; Playlists; Channels; Discussion; About ...");


        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikipedia.org/wiki/Anthony_Stafford_Beer", "https://en.wikipedia.org/wiki/Anthony_Stafford_Beer", "Stafford Beer - Wikipedia, the free encyclopedia", "Early life. Beer was born in Putney, London in 1926. At age 17 he was expelled from Whitgift School and enrolled for a degree in philosophy at University College London.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.amazon.co.uk/Stafford-Beer/e/B001HOTRSY", "www.amazon.co.uk/Stafford-Beer/e/B001HOTRSY", "Amazon.co.uk: Stafford Beer: Books, Biogs, Audiobooks ...", "Visit Amazon.co.uk's Stafford Beer Page and shop for all Stafford Beer books. Check out pictures, bibliography, biography and community discussions about Stafford Beer");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.cybsoc.org/contacts/people-Beer.htm", "www.cybsoc.org/contacts/people-Beer.htm", "The Cybernetics Society: In Memory of Stafford Beer", "The late Professor Stafford Beer bestrode Management as a colossus. In a series of ground breaking books culminating in 'Brain of the Firm... ''");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define(" http://www.flowmap.com/documents/vsm.pdf", "www.flowmap.com/documents/vsm.pdf", "Stafford Beer's Viable System Model - FlowMap", "Stafford Beerâ€™s Viable System Model An Interpretation By Trevor Hilder During the early 1990s my colleague, and ICT mentor, Trevor Hilder had the good");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikipedia.org/wiki/Viable_system_model", "https://en.wikipedia.org/wiki/Viable_system_model", "Viable system model - Wikipedia, the free encyclopedia", "Overview. The model was developed by operations research theorist and cybernetician Stafford Beer in his book Brain of the Firm (1972). Together with Beer's earlier ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www.amazon.co.uk/Diagnosing-System-Organizations-Classic-Beer/dp/0471951366", "https://www.amazon.co.uk/Diagnosing-System-Organizations-Classic...", "Diagnosing the System for Organizations (Classic Beer ...", "Buy Diagnosing the System for Organizations (Classic Beer Series) by Stafford Beer (ISBN: 9780471951360) from Amazon's Book Store. Free UK delivery on eligible orders.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.telegraph.co.uk/news/obituaries/1405557/Stafford-Beer.html", "www.telegraph.co.uk/news/obituaries/1405557/Stafford-Beer.html", "Stafford Beer - Telegraph", "Stafford Beer, who died on Friday aged 75, was a leading exponent of cybernetics, the theory devised in the 1940s by Norbert Wiener which applied lessons ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.staffordbeerfestival.org.uk/", "www.staffordbeerfestival.org.uk", "Stafford Beer and Cider Festival", "The Stafford branch of the Campaign for Real Ale (CAMRA) hold a Beer and Cider Festival every year at the Blessed William Howard School in stafford, from Thursday ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://wosc.co/outstanding-contributors/stafford-beer/", "wosc.co/outstanding-contributors/stafford-beer", "Stafford Beer | World Organisation of Systems and ...", "Stafford was larger than life. He was extraordinarily sensitive to his surroundings, able to perceive and make sense of the minutest signals, beyond the perception of ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.theguardian.com/news/2002/sep/04/guardianobituaries.obituaries", "www.theguardian.com/news/2002/sep/04/guardianobituaries.obituaries", "Obituary: Stafford Beer | Education | The Guardian", "Professor Stafford Beer, who has died aged 75, was a remarkable figure of British operational research (OR) - the study of systems that emerged from deploying newly ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.amazon.com/Stafford-Beer/e/B001HOTRSY/", "www.amazon.com/Stafford-Beer/e/B001HOTRSY", "Amazon.com: Stafford Beer: Books, Biography, Blog ...", "Visit Amazon.com's Stafford Beer Page and shop for all Stafford Beer books and other Stafford Beer related products (DVD, CDs, Apparel). Check out pictures ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.youtube.com/watch?v=JJ6orMfmorg", "www.youtube.com/watch?v=JJ6orMfmorg", "What is Cybernetics? Conference by Stafford Beer - YouTube", "Stafford Beer provides his explanation of what cybernetics is about. A must for anyone interested in the topic. This video belongs to John Moore University ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://en.wikiquote.org/wiki/Anthony_Stafford_Beer", "https://en.wikiquote.org/wiki/Anthony_Stafford_Beer", "Anthony Stafford Beer - Wikiquote", "Anthony Stafford Beer (September 25, 1926 â€“ August 23, 2002) was a British theorist, consultant and professor at the Manchester Business School.");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://www.theorsociety.com/Pages/Awards/Stafford.aspx", "www.theorsociety.com/Pages/Awards/Stafford.aspx", "The OR Society: Awards - The Stafford Beer Medal", "Awards - The Stafford Beer Medal. This award is named in memory of Stafford Beer, a world leader in the development of systems ideas, especially management ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://archiveshub.ac.uk/data/gb2993-sb", "archiveshub.ac.uk/data/gb2993-sb", "gb2993-sb - The Stafford Beer Collection - Archives Hub", "Scope and Content. The Stafford Beer Collection consists of almost 2000 books and pamphlets reflecting Professor Beer's wide-ranging interests and the development of ...");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("http://cybsoc.org/contacts/opendrunworld.pdf", "cybsoc.org/contacts/opendrunworld.pdf", "Stafford Beer: the man who could have run the world,", "www.openDemocracy.net 1 S tafford Beer, philosopher, scientist, poet, painter, founder of Management Cybernetics and world leader in operational");
        $this->urls[] = $aUrl; $aUrl = new SearchUrl(); $aUrl->define("https://www.ljmu.ac.uk/about-us/events/stafford-beer-and-cybernetics", "https://www.ljmu.ac.uk/about-us/events/stafford-beer-and-cybernetics", "Stafford Beer and Cybernetics | Liverpool John Moores ...", "Join LJMU on LightNight at Aldham Robarts Library to see a special exhibition and talk about Stafford Beer.");
        $this->urls[] = $aUrl;
    }
}


/**
 * @param $query
 */
function stubSearchFor($query){
    $returnUrls = array();

    $urlsToReturn = 20;
    
    $seleniumrc = new SearchUrl();
    $seleniumrc->define("http://seleniumhq.org", "seleniumhq.org", "Selenium Remote-Control", "Selenium RC comes in two parts. A server which automatically launches and kills browsers, and acts as a HTTP proxy for web requests from them. ...");

    if (strcasecmp($query,"selenium-rc")==0) {
        $returnUrls[] = $seleniumrc;
        $urlsToReturn--;
    }

    $urls = new SearchUrls();
    $urls->create();

    foreach($urls->get() as $sUrl){

        $addThis = false;

        if (strstr($sUrl->description,$query)) {
            $addThis = true;
        }

        if (strstr($sUrl->title,$query)) {
            $addThis = true;
        }

        if (strstr($sUrl->displayUrl,$query)) {
            $addThis = true;
        }

        if ($addThis) {
            $returnUrls[] = $sUrl;
            $urlsToReturn--;
        }

        if ($urlsToReturn == 0) {
            break;
        }
    }

    if ($urlsToReturn > 0) {
        // randomly choose some urls
        $theChosen = array_rand($urls->get(), $urlsToReturn);
        $returnUrls = array();
        foreach($theChosen as $sUrlKey) {
            array_push($returnUrls,$urls->getUrl($sUrlKey));
        }
    }

    return $returnUrls;
}

?>